/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.obcbo.cfbest;

import java.util.List;

public class App {
    public static void main(String[] args) {
        for (List<String> n : GetIP.get()) {
        System.out.println(n);
        }
    }
}
